model_id = "mlx-community/gemma-3n-E4B-it-4bit"
n_layers = 35
hidden_size = 2048
num_key_value_heads = 2
supports_tensor = false
tasks = ["TextGeneration"]
family = "gemma"
quantization = "4bit"
base_model = "Gemma 3n E4B"
capabilities = ["text", "vision"]

[vision]
image_token_id = 262145
model_type = "gemma3n"
boi_token_id = 255999
eoi_token_id = 262144

[storage_size]
in_bytes = 3200000000
